- hosts: all
  tasks:
    - name: set_version
      set_fact: os_version={{ ansible_distribution_version.split(".")[0:2]|join('.') }}

    - name: download chefdk
      when: ansible_os_family == "Darwin"
      get_url: 
        url: https://s3.amazonaws.com/happypathway-public-assets/chef/{{ ansible_os_family.lower() }}/{{ os_version }}/chefdk-2.5.3-1.dmg
        dest: /tmp/chefdk-2.5.3-1.dmg
      
    - name: download chefdk
      when: ansible_os_family == "Debian"
      get_url: 
        url: https://s3.amazonaws.com/happypathway-public-assets/chef/{{ ansible_os_family.lower() }}/{{ os_version }}/chefdk_2.5.3-1_amd64.deb
        dest: /tmp/chefdk-2.5.3-1.deb

    - name: install deb package
      when: ansible_os_family == "Debian"
      become: yes
      apt:
        deb: /tmp/chefdk-2.5.3-1.deb

    - name: open dmg
      delegate_to: localhost
      when: ansible_os_family == "Darwin"
      shell: open /tmp/chefdk-2.5.3-1.dmg
